### ISSUE TITLE
1.19 version and native libraries

### ISSUE THREAD

**Issue by Myszku** [MrShieh-X/minecraft-launcher-x#1]
Hey, there is an issue with downloading native libraries to launch Minecraft 1.19. It says that download native dependency libraries is completed, but it still unable to start the game. I think the program does not download these libraries.

**Comment by MrShieh-X** [comment]
Sorry, this launcher is no longer updated or maintained. If you want to use my launcher, go to https://github.com/MrShieh-X/console-minecraft-launcher and check out my new launcher CMCL.
(Note: CMCL is run using the console, that is to say, all operations are performed using commands, there is no graphical interface, please forgive me if you are not used to it: )
